// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: device.proto
package ug.hix.hixnet2.models

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class ACK(
  /**
   * this a one hop ack for the packets sent
   * ACKID is same as packetID of the original packet
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val ackID: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.PACKED
  )
  val expectedOffset: List<Int> = emptyList(),
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val toMeshID: String = "",
  /**
   * file or ""
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val type: String = "",
  unknownFields: ByteString = ByteString.EMPTY
) : Message<ACK, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ACK) return false
    return unknownFields == other.unknownFields
        && ackID == other.ackID
        && expectedOffset == other.expectedOffset
        && toMeshID == other.toMeshID
        && type == other.type
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + ackID.hashCode()
      result = result * 37 + expectedOffset.hashCode()
      result = result * 37 + toMeshID.hashCode()
      result = result * 37 + type.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """ackID=${sanitize(ackID)}"""
    if (expectedOffset.isNotEmpty()) result += """expectedOffset=$expectedOffset"""
    result += """toMeshID=${sanitize(toMeshID)}"""
    result += """type=${sanitize(type)}"""
    return result.joinToString(prefix = "ACK{", separator = ", ", postfix = "}")
  }

  fun copy(
    ackID: String = this.ackID,
    expectedOffset: List<Int> = this.expectedOffset,
    toMeshID: String = this.toMeshID,
    type: String = this.type,
    unknownFields: ByteString = this.unknownFields
  ): ACK = ACK(ackID, expectedOffset, toMeshID, type, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<ACK> = object : ProtoAdapter<ACK>(
      FieldEncoding.LENGTH_DELIMITED, 
      ACK::class, 
      "type.googleapis.com/ug.hix.hixnet2.models.ACK"
    ) {
      override fun encodedSize(value: ACK): Int = 
        ProtoAdapter.STRING.encodedSizeWithTag(1, value.ackID) +
        ProtoAdapter.INT32.asPacked().encodedSizeWithTag(2, value.expectedOffset) +
        ProtoAdapter.STRING.encodedSizeWithTag(3, value.toMeshID) +
        ProtoAdapter.STRING.encodedSizeWithTag(4, value.type) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: ACK) {
        if (value.ackID != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.ackID)
        ProtoAdapter.INT32.asPacked().encodeWithTag(writer, 2, value.expectedOffset)
        if (value.toMeshID != "") ProtoAdapter.STRING.encodeWithTag(writer, 3, value.toMeshID)
        if (value.type != "") ProtoAdapter.STRING.encodeWithTag(writer, 4, value.type)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): ACK {
        var ackID: String = ""
        val expectedOffset = mutableListOf<Int>()
        var toMeshID: String = ""
        var type: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> ackID = ProtoAdapter.STRING.decode(reader)
            2 -> expectedOffset.add(ProtoAdapter.INT32.decode(reader))
            3 -> toMeshID = ProtoAdapter.STRING.decode(reader)
            4 -> type = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ACK(
          ackID = ackID,
          expectedOffset = expectedOffset,
          toMeshID = toMeshID,
          type = type,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: ACK): ACK = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
