// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: device.proto
package ug.hix.hixnet2.models

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import com.squareup.wire.internal.redactElements
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Nothing
import kotlin.String
import kotlin.collections.List
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class FileHashMap(
  @field:WireField(
    tag = 1,
    adapter = "ug.hix.hixnet2.models.FileHashMap${'$'}CID#ADAPTER",
    label = WireField.Label.REPEATED
  )
  val cids: List<CID> = emptyList(),
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val operation: String = "",
  unknownFields: ByteString = ByteString.EMPTY
) : Message<FileHashMap, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is FileHashMap) return false
    return unknownFields == other.unknownFields
        && cids == other.cids
        && operation == other.operation
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + cids.hashCode()
      result = result * 37 + operation.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (cids.isNotEmpty()) result += """cids=$cids"""
    result += """operation=${sanitize(operation)}"""
    return result.joinToString(prefix = "FileHashMap{", separator = ", ", postfix = "}")
  }

  fun copy(
    cids: List<CID> = this.cids,
    operation: String = this.operation,
    unknownFields: ByteString = this.unknownFields
  ): FileHashMap = FileHashMap(cids, operation, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<FileHashMap> = object : ProtoAdapter<FileHashMap>(
      FieldEncoding.LENGTH_DELIMITED, 
      FileHashMap::class, 
      "type.googleapis.com/ug.hix.hixnet2.models.FileHashMap"
    ) {
      override fun encodedSize(value: FileHashMap): Int = 
        CID.ADAPTER.asRepeated().encodedSizeWithTag(1, value.cids) +
        ProtoAdapter.STRING.encodedSizeWithTag(2, value.operation) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: FileHashMap) {
        CID.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.cids)
        if (value.operation != "") ProtoAdapter.STRING.encodeWithTag(writer, 2, value.operation)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): FileHashMap {
        val cids = mutableListOf<CID>()
        var operation: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> cids.add(CID.ADAPTER.decode(reader))
            2 -> operation = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return FileHashMap(
          cids = cids,
          operation = operation,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: FileHashMap): FileHashMap = value.copy(
        cids = value.cids.redactElements(CID.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }
  }

  class Attributes(
    @field:WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
    )
    val key: String = "",
    @field:WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.REPEATED
    )
    val value: List<String> = emptyList(),
    unknownFields: ByteString = ByteString.EMPTY
  ) : Message<Attributes, Nothing>(ADAPTER, unknownFields) {
    @Deprecated(
      message = "Shouldn't be used in Kotlin",
      level = DeprecationLevel.HIDDEN
    )
    override fun newBuilder(): Nothing = throw AssertionError()

    override fun equals(other: Any?): Boolean {
      if (other === this) return true
      if (other !is Attributes) return false
      return unknownFields == other.unknownFields
          && key == other.key
          && value == other.value
    }

    override fun hashCode(): Int {
      var result = super.hashCode
      if (result == 0) {
        result = unknownFields.hashCode()
        result = result * 37 + key.hashCode()
        result = result * 37 + value.hashCode()
        super.hashCode = result
      }
      return result
    }

    override fun toString(): String {
      val result = mutableListOf<String>()
      result += """key=${sanitize(key)}"""
      if (value.isNotEmpty()) result += """value=${sanitize(value)}"""
      return result.joinToString(prefix = "Attributes{", separator = ", ", postfix = "}")
    }

    fun copy(
      key: String = this.key,
      value: List<String> = this.value,
      unknownFields: ByteString = this.unknownFields
    ): Attributes = Attributes(key, value, unknownFields)

    companion object {
      @JvmField
      val ADAPTER: ProtoAdapter<Attributes> = object : ProtoAdapter<Attributes>(
        FieldEncoding.LENGTH_DELIMITED, 
        Attributes::class, 
        "type.googleapis.com/ug.hix.hixnet2.models.FileHashMap.Attributes"
      ) {
        override fun encodedSize(value: Attributes): Int = 
          ProtoAdapter.STRING.encodedSizeWithTag(1, value.key) +
          ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(2, value.value) +
          value.unknownFields.size

        override fun encode(writer: ProtoWriter, value: Attributes) {
          if (value.key != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.key)
          ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.value)
          writer.writeBytes(value.unknownFields)
        }

        override fun decode(reader: ProtoReader): Attributes {
          var key: String = ""
          val value = mutableListOf<String>()
          val unknownFields = reader.forEachTag { tag ->
            when (tag) {
              1 -> key = ProtoAdapter.STRING.decode(reader)
              2 -> value.add(ProtoAdapter.STRING.decode(reader))
              else -> reader.readUnknownField(tag)
            }
          }
          return Attributes(
            key = key,
            value = value,
            unknownFields = unknownFields
          )
        }

        override fun redact(value: Attributes): Attributes = value.copy(
          unknownFields = ByteString.EMPTY
        )
      }
    }
  }

  class CID(
    @field:WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
    )
    val cid: String = "",
    @field:WireField(
      tag = 2,
      adapter = "ug.hix.hixnet2.models.FileHashMap${'$'}Attributes#ADAPTER",
      label = WireField.Label.REPEATED
    )
    val attributes: List<Attributes> = emptyList(),
    unknownFields: ByteString = ByteString.EMPTY
  ) : Message<CID, Nothing>(ADAPTER, unknownFields) {
    @Deprecated(
      message = "Shouldn't be used in Kotlin",
      level = DeprecationLevel.HIDDEN
    )
    override fun newBuilder(): Nothing = throw AssertionError()

    override fun equals(other: Any?): Boolean {
      if (other === this) return true
      if (other !is CID) return false
      return unknownFields == other.unknownFields
          && cid == other.cid
          && attributes == other.attributes
    }

    override fun hashCode(): Int {
      var result = super.hashCode
      if (result == 0) {
        result = unknownFields.hashCode()
        result = result * 37 + cid.hashCode()
        result = result * 37 + attributes.hashCode()
        super.hashCode = result
      }
      return result
    }

    override fun toString(): String {
      val result = mutableListOf<String>()
      result += """cid=${sanitize(cid)}"""
      if (attributes.isNotEmpty()) result += """attributes=$attributes"""
      return result.joinToString(prefix = "CID{", separator = ", ", postfix = "}")
    }

    fun copy(
      cid: String = this.cid,
      attributes: List<Attributes> = this.attributes,
      unknownFields: ByteString = this.unknownFields
    ): CID = CID(cid, attributes, unknownFields)

    companion object {
      @JvmField
      val ADAPTER: ProtoAdapter<CID> = object : ProtoAdapter<CID>(
        FieldEncoding.LENGTH_DELIMITED, 
        CID::class, 
        "type.googleapis.com/ug.hix.hixnet2.models.FileHashMap.CID"
      ) {
        override fun encodedSize(value: CID): Int = 
          ProtoAdapter.STRING.encodedSizeWithTag(1, value.cid) +
          Attributes.ADAPTER.asRepeated().encodedSizeWithTag(2, value.attributes) +
          value.unknownFields.size

        override fun encode(writer: ProtoWriter, value: CID) {
          if (value.cid != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.cid)
          Attributes.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.attributes)
          writer.writeBytes(value.unknownFields)
        }

        override fun decode(reader: ProtoReader): CID {
          var cid: String = ""
          val attributes = mutableListOf<Attributes>()
          val unknownFields = reader.forEachTag { tag ->
            when (tag) {
              1 -> cid = ProtoAdapter.STRING.decode(reader)
              2 -> attributes.add(Attributes.ADAPTER.decode(reader))
              else -> reader.readUnknownField(tag)
            }
          }
          return CID(
            cid = cid,
            attributes = attributes,
            unknownFields = unknownFields
          )
        }

        override fun redact(value: CID): CID = value.copy(
          attributes = value.attributes.redactElements(Attributes.ADAPTER),
          unknownFields = ByteString.EMPTY
        )
      }
    }
  }
}
