// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: device.proto
package ug.hix.hixnet2.models

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Nothing
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class PName(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val name: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val name_slub: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val modified_by: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val status: String = "",
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val modified: String = "",
  /**
   * helloAck hello nameUpdate
   */
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  val type: String = "",
  unknownFields: ByteString = ByteString.EMPTY
) : Message<PName, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  override fun newBuilder(): Nothing = throw AssertionError()

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PName) return false
    return unknownFields == other.unknownFields
        && name == other.name
        && name_slub == other.name_slub
        && modified_by == other.modified_by
        && status == other.status
        && modified == other.modified
        && type == other.type
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + name.hashCode()
      result = result * 37 + name_slub.hashCode()
      result = result * 37 + modified_by.hashCode()
      result = result * 37 + status.hashCode()
      result = result * 37 + modified.hashCode()
      result = result * 37 + type.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """name=${sanitize(name)}"""
    result += """name_slub=${sanitize(name_slub)}"""
    result += """modified_by=${sanitize(modified_by)}"""
    result += """status=${sanitize(status)}"""
    result += """modified=${sanitize(modified)}"""
    result += """type=${sanitize(type)}"""
    return result.joinToString(prefix = "PName{", separator = ", ", postfix = "}")
  }

  fun copy(
    name: String = this.name,
    name_slub: String = this.name_slub,
    modified_by: String = this.modified_by,
    status: String = this.status,
    modified: String = this.modified,
    type: String = this.type,
    unknownFields: ByteString = this.unknownFields
  ): PName = PName(name, name_slub, modified_by, status, modified, type, unknownFields)

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<PName> = object : ProtoAdapter<PName>(
      FieldEncoding.LENGTH_DELIMITED, 
      PName::class, 
      "type.googleapis.com/ug.hix.hixnet2.models.PName"
    ) {
      override fun encodedSize(value: PName): Int = 
        ProtoAdapter.STRING.encodedSizeWithTag(1, value.name) +
        ProtoAdapter.STRING.encodedSizeWithTag(2, value.name_slub) +
        ProtoAdapter.STRING.encodedSizeWithTag(3, value.modified_by) +
        ProtoAdapter.STRING.encodedSizeWithTag(4, value.status) +
        ProtoAdapter.STRING.encodedSizeWithTag(5, value.modified) +
        ProtoAdapter.STRING.encodedSizeWithTag(6, value.type) +
        value.unknownFields.size

      override fun encode(writer: ProtoWriter, value: PName) {
        if (value.name != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.name)
        if (value.name_slub != "") ProtoAdapter.STRING.encodeWithTag(writer, 2, value.name_slub)
        if (value.modified_by != "") ProtoAdapter.STRING.encodeWithTag(writer, 3, value.modified_by)
        if (value.status != "") ProtoAdapter.STRING.encodeWithTag(writer, 4, value.status)
        if (value.modified != "") ProtoAdapter.STRING.encodeWithTag(writer, 5, value.modified)
        if (value.type != "") ProtoAdapter.STRING.encodeWithTag(writer, 6, value.type)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): PName {
        var name: String = ""
        var name_slub: String = ""
        var modified_by: String = ""
        var status: String = ""
        var modified: String = ""
        var type: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> name = ProtoAdapter.STRING.decode(reader)
            2 -> name_slub = ProtoAdapter.STRING.decode(reader)
            3 -> modified_by = ProtoAdapter.STRING.decode(reader)
            4 -> status = ProtoAdapter.STRING.decode(reader)
            5 -> modified = ProtoAdapter.STRING.decode(reader)
            6 -> type = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return PName(
          name = name,
          name_slub = name_slub,
          modified_by = modified_by,
          status = status,
          modified = modified,
          type = type,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: PName): PName = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }
  }
}
